name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide details about what you'd like to see added.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see added?
      placeholder: Describe the feature you'd like to see implemented
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation and Use Case
      description: Why do you need this feature? What problem does it solve?
      placeholder: Explain the problem this feature would solve or the use case it would enable
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you think this should be implemented?
      placeholder: |
        - API design ideas
        - Implementation approach
        - Configuration options
        - Example usage

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
      placeholder: Describe any alternative solutions or features you've considered

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Bedrock Integration
        - CloudWatch Monitoring
        - Plugin Configuration
        - Examples
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this be a breaking change to existing APIs?
      options:
        - "No - Backwards compatible"
        - "Yes - Breaking change"
        - "Unsure"
    validations:
      required: true

  - type: textarea
    id: example-usage
    attributes:
      label: Example Usage
      description: Show how you envision using this feature
      render: go
      placeholder: |
        // Example of how the new feature would be used
        config := &genkitaws.Config{
            // Your example here
        }

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I am willing to help implement this feature
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or references
      placeholder: Add any other context, links, or screenshots about the feature request